databases:
  - name: urlshortdb
    databaseName: urlshortdb
    user: urlshortuser

services:
  - type: web
    name: urlshort
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn app.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urlshortdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
